package com.itoystergold.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class AssetRechargeSerial {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_recharge_serial.rid
     *
     * @mbggenerated
     */
    private String rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_recharge_serial.serialId
     *
     * @mbggenerated
     */
    private String serialid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_recharge_serial.request_param
     *
     * @mbggenerated
     */
    private String requestParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_recharge_serial.recharge_amt
     *
     * @mbggenerated
     */
    private BigDecimal rechargeAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_recharge_serial.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_recharge_serial.errcode
     *
     * @mbggenerated
     */
    private String errcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_recharge_serial.errmsg
     *
     * @mbggenerated
     */
    private String errmsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_recharge_serial.operator
     *
     * @mbggenerated
     */
    private String operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_recharge_serial.rechargetime
     *
     * @mbggenerated
     */
    private Date rechargetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_recharge_serial.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_recharge_serial.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_recharge_serial.rid
     *
     * @return the value of asset_recharge_serial.rid
     *
     * @mbggenerated
     */
    public String getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_recharge_serial.rid
     *
     * @param rid the value for asset_recharge_serial.rid
     *
     * @mbggenerated
     */
    public void setRid(String rid) {
        this.rid = rid == null ? null : rid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_recharge_serial.serialId
     *
     * @return the value of asset_recharge_serial.serialId
     *
     * @mbggenerated
     */
    public String getSerialid() {
        return serialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_recharge_serial.serialId
     *
     * @param serialid the value for asset_recharge_serial.serialId
     *
     * @mbggenerated
     */
    public void setSerialid(String serialid) {
        this.serialid = serialid == null ? null : serialid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_recharge_serial.request_param
     *
     * @return the value of asset_recharge_serial.request_param
     *
     * @mbggenerated
     */
    public String getRequestParam() {
        return requestParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_recharge_serial.request_param
     *
     * @param requestParam the value for asset_recharge_serial.request_param
     *
     * @mbggenerated
     */
    public void setRequestParam(String requestParam) {
        this.requestParam = requestParam == null ? null : requestParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_recharge_serial.recharge_amt
     *
     * @return the value of asset_recharge_serial.recharge_amt
     *
     * @mbggenerated
     */
    public BigDecimal getRechargeAmt() {
        return rechargeAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_recharge_serial.recharge_amt
     *
     * @param rechargeAmt the value for asset_recharge_serial.recharge_amt
     *
     * @mbggenerated
     */
    public void setRechargeAmt(BigDecimal rechargeAmt) {
        this.rechargeAmt = rechargeAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_recharge_serial.status
     *
     * @return the value of asset_recharge_serial.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_recharge_serial.status
     *
     * @param status the value for asset_recharge_serial.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_recharge_serial.errcode
     *
     * @return the value of asset_recharge_serial.errcode
     *
     * @mbggenerated
     */
    public String getErrcode() {
        return errcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_recharge_serial.errcode
     *
     * @param errcode the value for asset_recharge_serial.errcode
     *
     * @mbggenerated
     */
    public void setErrcode(String errcode) {
        this.errcode = errcode == null ? null : errcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_recharge_serial.errmsg
     *
     * @return the value of asset_recharge_serial.errmsg
     *
     * @mbggenerated
     */
    public String getErrmsg() {
        return errmsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_recharge_serial.errmsg
     *
     * @param errmsg the value for asset_recharge_serial.errmsg
     *
     * @mbggenerated
     */
    public void setErrmsg(String errmsg) {
        this.errmsg = errmsg == null ? null : errmsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_recharge_serial.operator
     *
     * @return the value of asset_recharge_serial.operator
     *
     * @mbggenerated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_recharge_serial.operator
     *
     * @param operator the value for asset_recharge_serial.operator
     *
     * @mbggenerated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_recharge_serial.rechargetime
     *
     * @return the value of asset_recharge_serial.rechargetime
     *
     * @mbggenerated
     */
    public Date getRechargetime() {
        return rechargetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_recharge_serial.rechargetime
     *
     * @param rechargetime the value for asset_recharge_serial.rechargetime
     *
     * @mbggenerated
     */
    public void setRechargetime(Date rechargetime) {
        this.rechargetime = rechargetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_recharge_serial.createtime
     *
     * @return the value of asset_recharge_serial.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_recharge_serial.createtime
     *
     * @param createtime the value for asset_recharge_serial.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_recharge_serial.updatetime
     *
     * @return the value of asset_recharge_serial.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_recharge_serial.updatetime
     *
     * @param updatetime the value for asset_recharge_serial.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}