package com.itoystergold.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class AssetPersonSalary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_person_salary.sid
     *
     * @mbggenerated
     */
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_person_salary.vid
     *
     * @mbggenerated
     */
    private String vid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_person_salary.oid
     *
     * @mbggenerated
     */
    private String oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_person_salary.salary
     *
     * @mbggenerated
     */
    private BigDecimal salary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_person_salary.salary_categery
     *
     * @mbggenerated
     */
    private String salaryCategery;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_person_salary.pldate
     *
     * @mbggenerated
     */
    private Date pldate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_person_salary.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_person_salary.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_person_salary.sid
     *
     * @return the value of asset_person_salary.sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_person_salary.sid
     *
     * @param sid the value for asset_person_salary.sid
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_person_salary.vid
     *
     * @return the value of asset_person_salary.vid
     *
     * @mbggenerated
     */
    public String getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_person_salary.vid
     *
     * @param vid the value for asset_person_salary.vid
     *
     * @mbggenerated
     */
    public void setVid(String vid) {
        this.vid = vid == null ? null : vid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_person_salary.oid
     *
     * @return the value of asset_person_salary.oid
     *
     * @mbggenerated
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_person_salary.oid
     *
     * @param oid the value for asset_person_salary.oid
     *
     * @mbggenerated
     */
    public void setOid(String oid) {
        this.oid = oid == null ? null : oid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_person_salary.salary
     *
     * @return the value of asset_person_salary.salary
     *
     * @mbggenerated
     */
    public BigDecimal getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_person_salary.salary
     *
     * @param salary the value for asset_person_salary.salary
     *
     * @mbggenerated
     */
    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_person_salary.salary_categery
     *
     * @return the value of asset_person_salary.salary_categery
     *
     * @mbggenerated
     */
    public String getSalaryCategery() {
        return salaryCategery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_person_salary.salary_categery
     *
     * @param salaryCategery the value for asset_person_salary.salary_categery
     *
     * @mbggenerated
     */
    public void setSalaryCategery(String salaryCategery) {
        this.salaryCategery = salaryCategery == null ? null : salaryCategery.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_person_salary.pldate
     *
     * @return the value of asset_person_salary.pldate
     *
     * @mbggenerated
     */
    public Date getPldate() {
        return pldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_person_salary.pldate
     *
     * @param pldate the value for asset_person_salary.pldate
     *
     * @mbggenerated
     */
    public void setPldate(Date pldate) {
        this.pldate = pldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_person_salary.createtime
     *
     * @return the value of asset_person_salary.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_person_salary.createtime
     *
     * @param createtime the value for asset_person_salary.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_person_salary.updatetime
     *
     * @return the value of asset_person_salary.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_person_salary.updatetime
     *
     * @param updatetime the value for asset_person_salary.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}