package com.itoystergold.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class AssetSalarySerial {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_salary_serial.sid
     *
     * @mbggenerated
     */
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_salary_serial.oid
     *
     * @mbggenerated
     */
    private String oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_salary_serial.vid
     *
     * @mbggenerated
     */
    private String vid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_salary_serial.salary
     *
     * @mbggenerated
     */
    private BigDecimal salary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_salary_serial.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_salary_serial.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_salary_serial.sid
     *
     * @return the value of asset_salary_serial.sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_salary_serial.sid
     *
     * @param sid the value for asset_salary_serial.sid
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_salary_serial.oid
     *
     * @return the value of asset_salary_serial.oid
     *
     * @mbggenerated
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_salary_serial.oid
     *
     * @param oid the value for asset_salary_serial.oid
     *
     * @mbggenerated
     */
    public void setOid(String oid) {
        this.oid = oid == null ? null : oid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_salary_serial.vid
     *
     * @return the value of asset_salary_serial.vid
     *
     * @mbggenerated
     */
    public String getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_salary_serial.vid
     *
     * @param vid the value for asset_salary_serial.vid
     *
     * @mbggenerated
     */
    public void setVid(String vid) {
        this.vid = vid == null ? null : vid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_salary_serial.salary
     *
     * @return the value of asset_salary_serial.salary
     *
     * @mbggenerated
     */
    public BigDecimal getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_salary_serial.salary
     *
     * @param salary the value for asset_salary_serial.salary
     *
     * @mbggenerated
     */
    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_salary_serial.createtime
     *
     * @return the value of asset_salary_serial.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_salary_serial.createtime
     *
     * @param createtime the value for asset_salary_serial.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_salary_serial.updatetime
     *
     * @return the value of asset_salary_serial.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_salary_serial.updatetime
     *
     * @param updatetime the value for asset_salary_serial.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}