package com.itoystergold.pojo;

import java.util.Date;

public class AssetSettleSerial {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_settle_serial.sid
     *
     * @mbggenerated
     */
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_settle_serial.serialId
     *
     * @mbggenerated
     */
    private String serialid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_settle_serial.request_param
     *
     * @mbggenerated
     */
    private String requestParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_settle_serial.handler_status
     *
     * @mbggenerated
     */
    private String handlerStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_settle_serial.errcode
     *
     * @mbggenerated
     */
    private String errcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_settle_serial.errmsg
     *
     * @mbggenerated
     */
    private String errmsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_settle_serial.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_settle_serial.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_settle_serial.sid
     *
     * @return the value of asset_settle_serial.sid
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_settle_serial.sid
     *
     * @param sid the value for asset_settle_serial.sid
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_settle_serial.serialId
     *
     * @return the value of asset_settle_serial.serialId
     *
     * @mbggenerated
     */
    public String getSerialid() {
        return serialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_settle_serial.serialId
     *
     * @param serialid the value for asset_settle_serial.serialId
     *
     * @mbggenerated
     */
    public void setSerialid(String serialid) {
        this.serialid = serialid == null ? null : serialid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_settle_serial.request_param
     *
     * @return the value of asset_settle_serial.request_param
     *
     * @mbggenerated
     */
    public String getRequestParam() {
        return requestParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_settle_serial.request_param
     *
     * @param requestParam the value for asset_settle_serial.request_param
     *
     * @mbggenerated
     */
    public void setRequestParam(String requestParam) {
        this.requestParam = requestParam == null ? null : requestParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_settle_serial.handler_status
     *
     * @return the value of asset_settle_serial.handler_status
     *
     * @mbggenerated
     */
    public String getHandlerStatus() {
        return handlerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_settle_serial.handler_status
     *
     * @param handlerStatus the value for asset_settle_serial.handler_status
     *
     * @mbggenerated
     */
    public void setHandlerStatus(String handlerStatus) {
        this.handlerStatus = handlerStatus == null ? null : handlerStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_settle_serial.errcode
     *
     * @return the value of asset_settle_serial.errcode
     *
     * @mbggenerated
     */
    public String getErrcode() {
        return errcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_settle_serial.errcode
     *
     * @param errcode the value for asset_settle_serial.errcode
     *
     * @mbggenerated
     */
    public void setErrcode(String errcode) {
        this.errcode = errcode == null ? null : errcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_settle_serial.errmsg
     *
     * @return the value of asset_settle_serial.errmsg
     *
     * @mbggenerated
     */
    public String getErrmsg() {
        return errmsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_settle_serial.errmsg
     *
     * @param errmsg the value for asset_settle_serial.errmsg
     *
     * @mbggenerated
     */
    public void setErrmsg(String errmsg) {
        this.errmsg = errmsg == null ? null : errmsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_settle_serial.createtime
     *
     * @return the value of asset_settle_serial.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_settle_serial.createtime
     *
     * @param createtime the value for asset_settle_serial.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_settle_serial.updatetime
     *
     * @return the value of asset_settle_serial.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_settle_serial.updatetime
     *
     * @param updatetime the value for asset_settle_serial.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}