package com.itoystergold.pojo;

import java.util.Date;

public class CCInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_info.cid
     *
     * @mbggenerated
     */
    private String cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_info.ctelephone
     *
     * @mbggenerated
     */
    private String ctelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_info.cname
     *
     * @mbggenerated
     */
    private String cname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_info.cvid
     *
     * @mbggenerated
     */
    private String cvid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_info.cparam
     *
     * @mbggenerated
     */
    private String cparam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_info.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_info.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cc_info.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_info.cid
     *
     * @return the value of cc_info.cid
     *
     * @mbggenerated
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_info.cid
     *
     * @param cid the value for cc_info.cid
     *
     * @mbggenerated
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_info.ctelephone
     *
     * @return the value of cc_info.ctelephone
     *
     * @mbggenerated
     */
    public String getCtelephone() {
        return ctelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_info.ctelephone
     *
     * @param ctelephone the value for cc_info.ctelephone
     *
     * @mbggenerated
     */
    public void setCtelephone(String ctelephone) {
        this.ctelephone = ctelephone == null ? null : ctelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_info.cname
     *
     * @return the value of cc_info.cname
     *
     * @mbggenerated
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_info.cname
     *
     * @param cname the value for cc_info.cname
     *
     * @mbggenerated
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_info.cvid
     *
     * @return the value of cc_info.cvid
     *
     * @mbggenerated
     */
    public String getCvid() {
        return cvid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_info.cvid
     *
     * @param cvid the value for cc_info.cvid
     *
     * @mbggenerated
     */
    public void setCvid(String cvid) {
        this.cvid = cvid == null ? null : cvid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_info.cparam
     *
     * @return the value of cc_info.cparam
     *
     * @mbggenerated
     */
    public String getCparam() {
        return cparam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_info.cparam
     *
     * @param cparam the value for cc_info.cparam
     *
     * @mbggenerated
     */
    public void setCparam(String cparam) {
        this.cparam = cparam == null ? null : cparam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_info.createtime
     *
     * @return the value of cc_info.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_info.createtime
     *
     * @param createtime the value for cc_info.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_info.updatetime
     *
     * @return the value of cc_info.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_info.updatetime
     *
     * @param updatetime the value for cc_info.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cc_info.type
     *
     * @return the value of cc_info.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cc_info.type
     *
     * @param type the value for cc_info.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}