package com.itoystergold.pojo;

public class DeploySubbankKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_subbank.SUB_NO
     *
     * @mbggenerated
     */
    private String subNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_subbank.TENANT_ID
     *
     * @mbggenerated
     */
    private String tenantId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_subbank.SUB_NO
     *
     * @return the value of deploy_subbank.SUB_NO
     *
     * @mbggenerated
     */
    public String getSubNo() {
        return subNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_subbank.SUB_NO
     *
     * @param subNo the value for deploy_subbank.SUB_NO
     *
     * @mbggenerated
     */
    public void setSubNo(String subNo) {
        this.subNo = subNo == null ? null : subNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_subbank.TENANT_ID
     *
     * @return the value of deploy_subbank.TENANT_ID
     *
     * @mbggenerated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_subbank.TENANT_ID
     *
     * @param tenantId the value for deploy_subbank.TENANT_ID
     *
     * @mbggenerated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }
}