package com.itoystergold.pojo;

public class DeployCardbins extends DeployCardbinsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_cardbins.BANK_ID
     *
     * @mbggenerated
     */
    private String bankId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_cardbins.CARDBIN
     *
     * @mbggenerated
     */
    private String cardbin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_cardbins.CARD_LENGTH
     *
     * @mbggenerated
     */
    private String cardLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_cardbins.MEMO
     *
     * @mbggenerated
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_cardbins.BANK_ID
     *
     * @return the value of deploy_cardbins.BANK_ID
     *
     * @mbggenerated
     */
    public String getBankId() {
        return bankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_cardbins.BANK_ID
     *
     * @param bankId the value for deploy_cardbins.BANK_ID
     *
     * @mbggenerated
     */
    public void setBankId(String bankId) {
        this.bankId = bankId == null ? null : bankId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_cardbins.CARDBIN
     *
     * @return the value of deploy_cardbins.CARDBIN
     *
     * @mbggenerated
     */
    public String getCardbin() {
        return cardbin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_cardbins.CARDBIN
     *
     * @param cardbin the value for deploy_cardbins.CARDBIN
     *
     * @mbggenerated
     */
    public void setCardbin(String cardbin) {
        this.cardbin = cardbin == null ? null : cardbin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_cardbins.CARD_LENGTH
     *
     * @return the value of deploy_cardbins.CARD_LENGTH
     *
     * @mbggenerated
     */
    public String getCardLength() {
        return cardLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_cardbins.CARD_LENGTH
     *
     * @param cardLength the value for deploy_cardbins.CARD_LENGTH
     *
     * @mbggenerated
     */
    public void setCardLength(String cardLength) {
        this.cardLength = cardLength == null ? null : cardLength.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_cardbins.MEMO
     *
     * @return the value of deploy_cardbins.MEMO
     *
     * @mbggenerated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_cardbins.MEMO
     *
     * @param memo the value for deploy_cardbins.MEMO
     *
     * @mbggenerated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}