package com.itoystergold.pojo;

public class DeploySubbank extends DeploySubbankKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_subbank.CLSBANK_NO
     *
     * @mbggenerated
     */
    private String clsbankNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_subbank.SUB_NAME
     *
     * @mbggenerated
     */
    private String subName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_subbank.SUB_SHORTNAME
     *
     * @mbggenerated
     */
    private String subShortname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_subbank.CITY_CODE
     *
     * @mbggenerated
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_subbank.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_subbank.CLSBANK_NO
     *
     * @return the value of deploy_subbank.CLSBANK_NO
     *
     * @mbggenerated
     */
    public String getClsbankNo() {
        return clsbankNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_subbank.CLSBANK_NO
     *
     * @param clsbankNo the value for deploy_subbank.CLSBANK_NO
     *
     * @mbggenerated
     */
    public void setClsbankNo(String clsbankNo) {
        this.clsbankNo = clsbankNo == null ? null : clsbankNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_subbank.SUB_NAME
     *
     * @return the value of deploy_subbank.SUB_NAME
     *
     * @mbggenerated
     */
    public String getSubName() {
        return subName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_subbank.SUB_NAME
     *
     * @param subName the value for deploy_subbank.SUB_NAME
     *
     * @mbggenerated
     */
    public void setSubName(String subName) {
        this.subName = subName == null ? null : subName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_subbank.SUB_SHORTNAME
     *
     * @return the value of deploy_subbank.SUB_SHORTNAME
     *
     * @mbggenerated
     */
    public String getSubShortname() {
        return subShortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_subbank.SUB_SHORTNAME
     *
     * @param subShortname the value for deploy_subbank.SUB_SHORTNAME
     *
     * @mbggenerated
     */
    public void setSubShortname(String subShortname) {
        this.subShortname = subShortname == null ? null : subShortname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_subbank.CITY_CODE
     *
     * @return the value of deploy_subbank.CITY_CODE
     *
     * @mbggenerated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_subbank.CITY_CODE
     *
     * @param cityCode the value for deploy_subbank.CITY_CODE
     *
     * @mbggenerated
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_subbank.STATUS
     *
     * @return the value of deploy_subbank.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_subbank.STATUS
     *
     * @param status the value for deploy_subbank.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}