package com.itoystergold.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class DeployLevelSalaryRule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_level_salary_rule.rid
     *
     * @mbggenerated
     */
    private String rid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_level_salary_rule.levelid
     *
     * @mbggenerated
     */
    private String levelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_level_salary_rule.introduce_rate
     *
     * @mbggenerated
     */
    private BigDecimal introduceRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_level_salary_rule.manage_rate
     *
     * @mbggenerated
     */
    private BigDecimal manageRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_level_salary_rule.service_amt
     *
     * @mbggenerated
     */
    private BigDecimal serviceAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_level_salary_rule.subsidy_amt
     *
     * @mbggenerated
     */
    private BigDecimal subsidyAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_level_salary_rule.share_rate
     *
     * @mbggenerated
     */
    private BigDecimal shareRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_level_salary_rule.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_level_salary_rule.updatetime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_level_salary_rule.rid
     *
     * @return the value of deploy_level_salary_rule.rid
     *
     * @mbggenerated
     */
    public String getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_level_salary_rule.rid
     *
     * @param rid the value for deploy_level_salary_rule.rid
     *
     * @mbggenerated
     */
    public void setRid(String rid) {
        this.rid = rid == null ? null : rid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_level_salary_rule.levelid
     *
     * @return the value of deploy_level_salary_rule.levelid
     *
     * @mbggenerated
     */
    public String getLevelid() {
        return levelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_level_salary_rule.levelid
     *
     * @param levelid the value for deploy_level_salary_rule.levelid
     *
     * @mbggenerated
     */
    public void setLevelid(String levelid) {
        this.levelid = levelid == null ? null : levelid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_level_salary_rule.introduce_rate
     *
     * @return the value of deploy_level_salary_rule.introduce_rate
     *
     * @mbggenerated
     */
    public BigDecimal getIntroduceRate() {
        return introduceRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_level_salary_rule.introduce_rate
     *
     * @param introduceRate the value for deploy_level_salary_rule.introduce_rate
     *
     * @mbggenerated
     */
    public void setIntroduceRate(BigDecimal introduceRate) {
        this.introduceRate = introduceRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_level_salary_rule.manage_rate
     *
     * @return the value of deploy_level_salary_rule.manage_rate
     *
     * @mbggenerated
     */
    public BigDecimal getManageRate() {
        return manageRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_level_salary_rule.manage_rate
     *
     * @param manageRate the value for deploy_level_salary_rule.manage_rate
     *
     * @mbggenerated
     */
    public void setManageRate(BigDecimal manageRate) {
        this.manageRate = manageRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_level_salary_rule.service_amt
     *
     * @return the value of deploy_level_salary_rule.service_amt
     *
     * @mbggenerated
     */
    public BigDecimal getServiceAmt() {
        return serviceAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_level_salary_rule.service_amt
     *
     * @param serviceAmt the value for deploy_level_salary_rule.service_amt
     *
     * @mbggenerated
     */
    public void setServiceAmt(BigDecimal serviceAmt) {
        this.serviceAmt = serviceAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_level_salary_rule.subsidy_amt
     *
     * @return the value of deploy_level_salary_rule.subsidy_amt
     *
     * @mbggenerated
     */
    public BigDecimal getSubsidyAmt() {
        return subsidyAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_level_salary_rule.subsidy_amt
     *
     * @param subsidyAmt the value for deploy_level_salary_rule.subsidy_amt
     *
     * @mbggenerated
     */
    public void setSubsidyAmt(BigDecimal subsidyAmt) {
        this.subsidyAmt = subsidyAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_level_salary_rule.share_rate
     *
     * @return the value of deploy_level_salary_rule.share_rate
     *
     * @mbggenerated
     */
    public BigDecimal getShareRate() {
        return shareRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_level_salary_rule.share_rate
     *
     * @param shareRate the value for deploy_level_salary_rule.share_rate
     *
     * @mbggenerated
     */
    public void setShareRate(BigDecimal shareRate) {
        this.shareRate = shareRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_level_salary_rule.createtime
     *
     * @return the value of deploy_level_salary_rule.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_level_salary_rule.createtime
     *
     * @param createtime the value for deploy_level_salary_rule.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_level_salary_rule.updatetime
     *
     * @return the value of deploy_level_salary_rule.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_level_salary_rule.updatetime
     *
     * @param updatetime the value for deploy_level_salary_rule.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}