package com.itoystergold.pojo;

public class DeployCity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_city.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_city.CODE
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_city.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deploy_city.PROVINCE_CODE
     *
     * @mbggenerated
     */
    private String provinceCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_city.id
     *
     * @return the value of deploy_city.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_city.id
     *
     * @param id the value for deploy_city.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_city.CODE
     *
     * @return the value of deploy_city.CODE
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_city.CODE
     *
     * @param code the value for deploy_city.CODE
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_city.NAME
     *
     * @return the value of deploy_city.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_city.NAME
     *
     * @param name the value for deploy_city.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deploy_city.PROVINCE_CODE
     *
     * @return the value of deploy_city.PROVINCE_CODE
     *
     * @mbggenerated
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deploy_city.PROVINCE_CODE
     *
     * @param provinceCode the value for deploy_city.PROVINCE_CODE
     *
     * @mbggenerated
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }
}