package com.itoystergold.pojo;

import java.util.Date;

public class Module {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.module_id
     *
     * @mbggenerated
     */
    private String moduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.parent_id
     *
     * @mbggenerated
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.parent_name
     *
     * @mbggenerated
     */
    private String parentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.layer_num
     *
     * @mbggenerated
     */
    private Integer layerNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.is_leaf
     *
     * @mbggenerated
     */
    private Integer isLeaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.ico
     *
     * @mbggenerated
     */
    private String ico;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.cpermission
     *
     * @mbggenerated
     */
    private String cpermission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.curl
     *
     * @mbggenerated
     */
    private String curl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.ctype
     *
     * @mbggenerated
     */
    private Integer ctype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.belong
     *
     * @mbggenerated
     */
    private String belong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.cwhich
     *
     * @mbggenerated
     */
    private String cwhich;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.quote_num
     *
     * @mbggenerated
     */
    private Integer quoteNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.order_no
     *
     * @mbggenerated
     */
    private Integer orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.create_dept
     *
     * @mbggenerated
     */
    private String createDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.module_id
     *
     * @return the value of module.module_id
     *
     * @mbggenerated
     */
    public String getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.module_id
     *
     * @param moduleId the value for module.module_id
     *
     * @mbggenerated
     */
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId == null ? null : moduleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.parent_id
     *
     * @return the value of module.parent_id
     *
     * @mbggenerated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.parent_id
     *
     * @param parentId the value for module.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.parent_name
     *
     * @return the value of module.parent_name
     *
     * @mbggenerated
     */
    public String getParentName() {
        return parentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.parent_name
     *
     * @param parentName the value for module.parent_name
     *
     * @mbggenerated
     */
    public void setParentName(String parentName) {
        this.parentName = parentName == null ? null : parentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.name
     *
     * @return the value of module.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.name
     *
     * @param name the value for module.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.layer_num
     *
     * @return the value of module.layer_num
     *
     * @mbggenerated
     */
    public Integer getLayerNum() {
        return layerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.layer_num
     *
     * @param layerNum the value for module.layer_num
     *
     * @mbggenerated
     */
    public void setLayerNum(Integer layerNum) {
        this.layerNum = layerNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.is_leaf
     *
     * @return the value of module.is_leaf
     *
     * @mbggenerated
     */
    public Integer getIsLeaf() {
        return isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.is_leaf
     *
     * @param isLeaf the value for module.is_leaf
     *
     * @mbggenerated
     */
    public void setIsLeaf(Integer isLeaf) {
        this.isLeaf = isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.ico
     *
     * @return the value of module.ico
     *
     * @mbggenerated
     */
    public String getIco() {
        return ico;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.ico
     *
     * @param ico the value for module.ico
     *
     * @mbggenerated
     */
    public void setIco(String ico) {
        this.ico = ico == null ? null : ico.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.cpermission
     *
     * @return the value of module.cpermission
     *
     * @mbggenerated
     */
    public String getCpermission() {
        return cpermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.cpermission
     *
     * @param cpermission the value for module.cpermission
     *
     * @mbggenerated
     */
    public void setCpermission(String cpermission) {
        this.cpermission = cpermission == null ? null : cpermission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.curl
     *
     * @return the value of module.curl
     *
     * @mbggenerated
     */
    public String getCurl() {
        return curl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.curl
     *
     * @param curl the value for module.curl
     *
     * @mbggenerated
     */
    public void setCurl(String curl) {
        this.curl = curl == null ? null : curl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.ctype
     *
     * @return the value of module.ctype
     *
     * @mbggenerated
     */
    public Integer getCtype() {
        return ctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.ctype
     *
     * @param ctype the value for module.ctype
     *
     * @mbggenerated
     */
    public void setCtype(Integer ctype) {
        this.ctype = ctype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.state
     *
     * @return the value of module.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.state
     *
     * @param state the value for module.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.belong
     *
     * @return the value of module.belong
     *
     * @mbggenerated
     */
    public String getBelong() {
        return belong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.belong
     *
     * @param belong the value for module.belong
     *
     * @mbggenerated
     */
    public void setBelong(String belong) {
        this.belong = belong == null ? null : belong.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.cwhich
     *
     * @return the value of module.cwhich
     *
     * @mbggenerated
     */
    public String getCwhich() {
        return cwhich;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.cwhich
     *
     * @param cwhich the value for module.cwhich
     *
     * @mbggenerated
     */
    public void setCwhich(String cwhich) {
        this.cwhich = cwhich == null ? null : cwhich.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.quote_num
     *
     * @return the value of module.quote_num
     *
     * @mbggenerated
     */
    public Integer getQuoteNum() {
        return quoteNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.quote_num
     *
     * @param quoteNum the value for module.quote_num
     *
     * @mbggenerated
     */
    public void setQuoteNum(Integer quoteNum) {
        this.quoteNum = quoteNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.remark
     *
     * @return the value of module.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.remark
     *
     * @param remark the value for module.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.order_no
     *
     * @return the value of module.order_no
     *
     * @mbggenerated
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.order_no
     *
     * @param orderNo the value for module.order_no
     *
     * @mbggenerated
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.create_by
     *
     * @return the value of module.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.create_by
     *
     * @param createBy the value for module.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.create_dept
     *
     * @return the value of module.create_dept
     *
     * @mbggenerated
     */
    public String getCreateDept() {
        return createDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.create_dept
     *
     * @param createDept the value for module.create_dept
     *
     * @mbggenerated
     */
    public void setCreateDept(String createDept) {
        this.createDept = createDept == null ? null : createDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.create_time
     *
     * @return the value of module.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.create_time
     *
     * @param createTime the value for module.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.update_by
     *
     * @return the value of module.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.update_by
     *
     * @param updateBy the value for module.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module.update_time
     *
     * @return the value of module.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module.update_time
     *
     * @param updateTime the value for module.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}