package com.itoystergold.pojo;

public class VipCar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_car.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_car.item_id
     *
     * @mbggenerated
     */
    private String itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_car.vipid
     *
     * @mbggenerated
     */
    private String vipid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_car.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_car.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_car.price
     *
     * @mbggenerated
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_car.total_fee
     *
     * @mbggenerated
     */
    private Long totalFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vip_car.pic_path
     *
     * @mbggenerated
     */
    private String picPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_car.id
     *
     * @return the value of vip_car.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_car.id
     *
     * @param id the value for vip_car.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_car.item_id
     *
     * @return the value of vip_car.item_id
     *
     * @mbggenerated
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_car.item_id
     *
     * @param itemId the value for vip_car.item_id
     *
     * @mbggenerated
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_car.vipid
     *
     * @return the value of vip_car.vipid
     *
     * @mbggenerated
     */
    public String getVipid() {
        return vipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_car.vipid
     *
     * @param vipid the value for vip_car.vipid
     *
     * @mbggenerated
     */
    public void setVipid(String vipid) {
        this.vipid = vipid == null ? null : vipid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_car.num
     *
     * @return the value of vip_car.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_car.num
     *
     * @param num the value for vip_car.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_car.title
     *
     * @return the value of vip_car.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_car.title
     *
     * @param title the value for vip_car.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_car.price
     *
     * @return the value of vip_car.price
     *
     * @mbggenerated
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_car.price
     *
     * @param price the value for vip_car.price
     *
     * @mbggenerated
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_car.total_fee
     *
     * @return the value of vip_car.total_fee
     *
     * @mbggenerated
     */
    public Long getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_car.total_fee
     *
     * @param totalFee the value for vip_car.total_fee
     *
     * @mbggenerated
     */
    public void setTotalFee(Long totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vip_car.pic_path
     *
     * @return the value of vip_car.pic_path
     *
     * @mbggenerated
     */
    public String getPicPath() {
        return picPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vip_car.pic_path
     *
     * @param picPath the value for vip_car.pic_path
     *
     * @mbggenerated
     */
    public void setPicPath(String picPath) {
        this.picPath = picPath == null ? null : picPath.trim();
    }
}