package com.itoystergold.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.itoystergold.pojo.AccountRevenue;
import com.itoystergold.pojo.AccountRevenueExample;

public interface AccountRevenueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_revenue
     *
     * @mbggenerated
     */
    int countByExample(AccountRevenueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_revenue
     *
     * @mbggenerated
     */
    int deleteByExample(AccountRevenueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_revenue
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_revenue
     *
     * @mbggenerated
     */
    int insert(AccountRevenue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_revenue
     *
     * @mbggenerated
     */
    int insertSelective(AccountRevenue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_revenue
     *
     * @mbggenerated
     */
    List<AccountRevenue> selectByExample(AccountRevenueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_revenue
     *
     * @mbggenerated
     */
    AccountRevenue selectByPrimaryKey(String aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_revenue
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AccountRevenue record, @Param("example") AccountRevenueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_revenue
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AccountRevenue record, @Param("example") AccountRevenueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_revenue
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AccountRevenue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_revenue
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AccountRevenue record);
}