package com.itoystergold.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.itoystergold.pojo.AssetCashSerial;
import com.itoystergold.pojo.AssetCashSerialExample;

public interface AssetCashSerialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_cash_serial
     *
     * @mbggenerated
     */
    int countByExample(AssetCashSerialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_cash_serial
     *
     * @mbggenerated
     */
    int deleteByExample(AssetCashSerialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_cash_serial
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_cash_serial
     *
     * @mbggenerated
     */
    int insert(AssetCashSerial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_cash_serial
     *
     * @mbggenerated
     */
    int insertSelective(AssetCashSerial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_cash_serial
     *
     * @mbggenerated
     */
    List<AssetCashSerial> selectByExample(AssetCashSerialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_cash_serial
     *
     * @mbggenerated
     */
    AssetCashSerial selectByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_cash_serial
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AssetCashSerial record, @Param("example") AssetCashSerialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_cash_serial
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AssetCashSerial record, @Param("example") AssetCashSerialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_cash_serial
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AssetCashSerial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_cash_serial
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AssetCashSerial record);
}