package com.itoystergold.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.itoystergold.pojo.AssetSalarySerial;
import com.itoystergold.pojo.AssetSalarySerialExample;

public interface AssetSalarySerialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_salary_serial
     *
     * @mbggenerated
     */
    int countByExample(AssetSalarySerialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_salary_serial
     *
     * @mbggenerated
     */
    int deleteByExample(AssetSalarySerialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_salary_serial
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_salary_serial
     *
     * @mbggenerated
     */
    int insert(AssetSalarySerial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_salary_serial
     *
     * @mbggenerated
     */
    int insertSelective(AssetSalarySerial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_salary_serial
     *
     * @mbggenerated
     */
    List<AssetSalarySerial> selectByExample(AssetSalarySerialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_salary_serial
     *
     * @mbggenerated
     */
    AssetSalarySerial selectByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_salary_serial
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AssetSalarySerial record, @Param("example") AssetSalarySerialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_salary_serial
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AssetSalarySerial record, @Param("example") AssetSalarySerialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_salary_serial
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AssetSalarySerial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_salary_serial
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AssetSalarySerial record);
}