package com.itoystergold.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.itoystergold.pojo.AssetStock;
import com.itoystergold.pojo.AssetStockExample;

public interface AssetStockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_stock
     *
     * @mbggenerated
     */
    int countByExample(AssetStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_stock
     *
     * @mbggenerated
     */
    int deleteByExample(AssetStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_stock
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_stock
     *
     * @mbggenerated
     */
    int insert(AssetStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_stock
     *
     * @mbggenerated
     */
    int insertSelective(AssetStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_stock
     *
     * @mbggenerated
     */
    List<AssetStock> selectByExample(AssetStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_stock
     *
     * @mbggenerated
     */
    AssetStock selectByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_stock
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AssetStock record, @Param("example") AssetStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_stock
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AssetStock record, @Param("example") AssetStockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_stock
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AssetStock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_stock
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AssetStock record);
}