package com.itoystergold.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.itoystergold.pojo.AssetTransSerial;
import com.itoystergold.pojo.AssetTransSerialExample;

public interface AssetTransSerialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_trans_serail
     *
     * @mbggenerated
     */
    int countByExample(AssetTransSerialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_trans_serail
     *
     * @mbggenerated
     */
    int deleteByExample(AssetTransSerialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_trans_serail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_trans_serail
     *
     * @mbggenerated
     */
    int insert(AssetTransSerial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_trans_serail
     *
     * @mbggenerated
     */
    int insertSelective(AssetTransSerial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_trans_serail
     *
     * @mbggenerated
     */
    List<AssetTransSerial> selectByExample(AssetTransSerialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_trans_serail
     *
     * @mbggenerated
     */
    AssetTransSerial selectByPrimaryKey(String tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_trans_serail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AssetTransSerial record, @Param("example") AssetTransSerialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_trans_serail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AssetTransSerial record, @Param("example") AssetTransSerialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_trans_serail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AssetTransSerial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_trans_serail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AssetTransSerial record);
}