package com.itoystergold.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.itoystergold.pojo.AssetSettleSerial;
import com.itoystergold.pojo.AssetSettleSerialExample;

public interface AssetSettleSerialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_settle_serial
     *
     * @mbggenerated
     */
    int countByExample(AssetSettleSerialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_settle_serial
     *
     * @mbggenerated
     */
    int deleteByExample(AssetSettleSerialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_settle_serial
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_settle_serial
     *
     * @mbggenerated
     */
    int insert(AssetSettleSerial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_settle_serial
     *
     * @mbggenerated
     */
    int insertSelective(AssetSettleSerial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_settle_serial
     *
     * @mbggenerated
     */
    List<AssetSettleSerial> selectByExample(AssetSettleSerialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_settle_serial
     *
     * @mbggenerated
     */
    AssetSettleSerial selectByPrimaryKey(String sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_settle_serial
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") AssetSettleSerial record, @Param("example") AssetSettleSerialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_settle_serial
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") AssetSettleSerial record, @Param("example") AssetSettleSerialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_settle_serial
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AssetSettleSerial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_settle_serial
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AssetSettleSerial record);
}