package com.itoystergold.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.itoystergold.pojo.DeployCardbins;
import com.itoystergold.pojo.DeployCardbinsExample;
import com.itoystergold.pojo.DeployCardbinsKey;

public interface DeployCardbinsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_cardbins
     *
     * @mbggenerated
     */
    int countByExample(DeployCardbinsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_cardbins
     *
     * @mbggenerated
     */
    int deleteByExample(DeployCardbinsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_cardbins
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(DeployCardbinsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_cardbins
     *
     * @mbggenerated
     */
    int insert(DeployCardbins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_cardbins
     *
     * @mbggenerated
     */
    int insertSelective(DeployCardbins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_cardbins
     *
     * @mbggenerated
     */
    List<DeployCardbins> selectByExample(DeployCardbinsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_cardbins
     *
     * @mbggenerated
     */
    DeployCardbins selectByPrimaryKey(DeployCardbinsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_cardbins
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DeployCardbins record, @Param("example") DeployCardbinsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_cardbins
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DeployCardbins record, @Param("example") DeployCardbinsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_cardbins
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DeployCardbins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_cardbins
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DeployCardbins record);
}