package com.itoystergold.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.itoystergold.pojo.DeployLevel;
import com.itoystergold.pojo.DeployLevelExample;

public interface DeployLevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_level
     *
     * @mbggenerated
     */
    int countByExample(DeployLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_level
     *
     * @mbggenerated
     */
    int deleteByExample(DeployLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_level
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_level
     *
     * @mbggenerated
     */
    int insert(DeployLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_level
     *
     * @mbggenerated
     */
    int insertSelective(DeployLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_level
     *
     * @mbggenerated
     */
    List<DeployLevel> selectByExample(DeployLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_level
     *
     * @mbggenerated
     */
    DeployLevel selectByPrimaryKey(String lid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_level
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DeployLevel record, @Param("example") DeployLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_level
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DeployLevel record, @Param("example") DeployLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_level
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DeployLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_level
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DeployLevel record);
}