package com.itoystergold.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.itoystergold.pojo.DeploySubbank;
import com.itoystergold.pojo.DeploySubbankExample;
import com.itoystergold.pojo.DeploySubbankKey;

public interface DeploySubbankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_subbank
     *
     * @mbggenerated
     */
    int countByExample(DeploySubbankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_subbank
     *
     * @mbggenerated
     */
    int deleteByExample(DeploySubbankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_subbank
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(DeploySubbankKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_subbank
     *
     * @mbggenerated
     */
    int insert(DeploySubbank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_subbank
     *
     * @mbggenerated
     */
    int insertSelective(DeploySubbank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_subbank
     *
     * @mbggenerated
     */
    List<DeploySubbank> selectByExample(DeploySubbankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_subbank
     *
     * @mbggenerated
     */
    DeploySubbank selectByPrimaryKey(DeploySubbankKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_subbank
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DeploySubbank record, @Param("example") DeploySubbankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_subbank
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DeploySubbank record, @Param("example") DeploySubbankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_subbank
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DeploySubbank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_subbank
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DeploySubbank record);
}