package com.itoystergold.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.itoystergold.pojo.DeployCity;
import com.itoystergold.pojo.DeployCityExample;

public interface DeployCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_city
     *
     * @mbggenerated
     */
    int countByExample(DeployCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_city
     *
     * @mbggenerated
     */
    int deleteByExample(DeployCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_city
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_city
     *
     * @mbggenerated
     */
    int insert(DeployCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_city
     *
     * @mbggenerated
     */
    int insertSelective(DeployCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_city
     *
     * @mbggenerated
     */
    List<DeployCity> selectByExample(DeployCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_city
     *
     * @mbggenerated
     */
    DeployCity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_city
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DeployCity record, @Param("example") DeployCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_city
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DeployCity record, @Param("example") DeployCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_city
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DeployCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_city
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DeployCity record);
}