package com.itoystergold.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.itoystergold.pojo.DeployClsbank;
import com.itoystergold.pojo.DeployClsbankExample;
import com.itoystergold.pojo.DeployClsbankKey;

public interface DeployClsbankMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_clsbank
     *
     * @mbggenerated
     */
    int countByExample(DeployClsbankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_clsbank
     *
     * @mbggenerated
     */
    int deleteByExample(DeployClsbankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_clsbank
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(DeployClsbankKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_clsbank
     *
     * @mbggenerated
     */
    int insert(DeployClsbank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_clsbank
     *
     * @mbggenerated
     */
    int insertSelective(DeployClsbank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_clsbank
     *
     * @mbggenerated
     */
    List<DeployClsbank> selectByExample(DeployClsbankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_clsbank
     *
     * @mbggenerated
     */
    DeployClsbank selectByPrimaryKey(DeployClsbankKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_clsbank
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DeployClsbank record, @Param("example") DeployClsbankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_clsbank
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DeployClsbank record, @Param("example") DeployClsbankExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_clsbank
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DeployClsbank record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_clsbank
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DeployClsbank record);
}