package com.itoystergold.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.itoystergold.pojo.DeployArea;
import com.itoystergold.pojo.DeployAreaExample;

public interface DeployAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_area
     *
     * @mbggenerated
     */
    int countByExample(DeployAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_area
     *
     * @mbggenerated
     */
    int deleteByExample(DeployAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_area
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_area
     *
     * @mbggenerated
     */
    int insert(DeployArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_area
     *
     * @mbggenerated
     */
    int insertSelective(DeployArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_area
     *
     * @mbggenerated
     */
    List<DeployArea> selectByExample(DeployAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_area
     *
     * @mbggenerated
     */
    DeployArea selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_area
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DeployArea record, @Param("example") DeployAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_area
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DeployArea record, @Param("example") DeployAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_area
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DeployArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_area
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DeployArea record);
}