package com.itoystergold.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.itoystergold.pojo.DeployLevelSalaryRule;
import com.itoystergold.pojo.DeployLevelSalaryRuleExample;

public interface DeployLevelSalaryRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_level_salary_rule
     *
     * @mbggenerated
     */
    int countByExample(DeployLevelSalaryRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_level_salary_rule
     *
     * @mbggenerated
     */
    int deleteByExample(DeployLevelSalaryRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_level_salary_rule
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_level_salary_rule
     *
     * @mbggenerated
     */
    int insert(DeployLevelSalaryRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_level_salary_rule
     *
     * @mbggenerated
     */
    int insertSelective(DeployLevelSalaryRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_level_salary_rule
     *
     * @mbggenerated
     */
    List<DeployLevelSalaryRule> selectByExample(DeployLevelSalaryRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_level_salary_rule
     *
     * @mbggenerated
     */
    DeployLevelSalaryRule selectByPrimaryKey(String rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_level_salary_rule
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DeployLevelSalaryRule record, @Param("example") DeployLevelSalaryRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_level_salary_rule
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DeployLevelSalaryRule record, @Param("example") DeployLevelSalaryRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_level_salary_rule
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DeployLevelSalaryRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deploy_level_salary_rule
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DeployLevelSalaryRule record);
}