package com.itoystergold.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.itoystergold.pojo.VipCar;
import com.itoystergold.pojo.VipCarExample;

public interface VipCarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_car
     *
     * @mbggenerated
     */
    int countByExample(VipCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_car
     *
     * @mbggenerated
     */
    int deleteByExample(VipCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_car
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_car
     *
     * @mbggenerated
     */
    int insert(VipCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_car
     *
     * @mbggenerated
     */
    int insertSelective(VipCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_car
     *
     * @mbggenerated
     */
    List<VipCar> selectByExample(VipCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_car
     *
     * @mbggenerated
     */
    VipCar selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_car
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") VipCar record, @Param("example") VipCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_car
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") VipCar record, @Param("example") VipCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_car
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VipCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vip_car
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VipCar record);
}